import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "index",
    "about/vision",
    "about/why-the-core-stays-thin",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/index",
        "getting-started/installation",
        "getting-started/quick-start",
        "getting-started/provider-setup",
        "getting-started/environment-variables",
        "getting-started/redis-quickstart",
        {
          type: "category",
          label: "Providers",
          collapsed: true,
          items: [
            "getting-started/providers/index",
            "getting-started/providers/typesafe",
            "getting-started/providers/laya",
            "getting-started/providers/xor",
            "getting-started/providers/openai",
            "getting-started/providers/anthropic",
            "getting-started/providers/google-ai",
            "getting-started/providers/google-vertex",
            "getting-started/providers/aws-bedrock",
            "getting-started/providers/azure-openai",
            "getting-started/providers/mistral",
            "getting-started/providers/huggingface",
            "getting-started/providers/ollama",
            "getting-started/providers/litellm",
            "getting-started/providers/sagemaker",
            "getting-started/providers/openrouter",
            "getting-started/providers/flatkey",
            "getting-started/providers/openai-compatible",
            "getting-started/providers/deepseek",
            "getting-started/providers/nvidia-nim",
            "getting-started/providers/lm-studio",
            "getting-started/providers/llamacpp",
            "getting-started/providers/above-dev",
            "getting-started/providers/ai21",
            "getting-started/providers/aiand",
            "getting-started/providers/aionlabs",
            "getting-started/providers/ambient",
            "getting-started/providers/api-route",
            "getting-started/providers/arcee",
            "getting-started/providers/atlas-cloud",
            "getting-started/providers/avian-io",
            "getting-started/providers/baidu-qianfan",
            "getting-started/providers/baseten",
            "getting-started/providers/bee-heossi",
            "getting-started/providers/byteplus-modelark",
            "getting-started/providers/bytez",
            "getting-started/providers/cerebras",
            "getting-started/providers/charm-hyper",
            "getting-started/providers/chutes",
            "getting-started/providers/cloudflare",
            "getting-started/providers/cohere",
            "getting-started/providers/crusoe",
            "getting-started/providers/dashscope",
            "getting-started/providers/deepinfra",
            "getting-started/providers/empiriolabs",
            "getting-started/providers/featherless-ai",
            "getting-started/providers/fireworks",
            "getting-started/providers/friendli",
            "getting-started/providers/gmicloud",
            "getting-started/providers/gradientai",
            "getting-started/providers/groq",
            "getting-started/providers/hetzner-inference",
            "getting-started/providers/inception-labs",
            "getting-started/providers/inceptron",
            "getting-started/providers/inco",
            "getting-started/providers/inference-net",
            "getting-started/providers/io-intelligence",
            "getting-started/providers/koscompute",
            "getting-started/providers/lemonfox-ai",
            "getting-started/providers/lilac",
            "getting-started/providers/llmtech",
            "getting-started/providers/mancer",
            "getting-started/providers/meta-model-api",
            "getting-started/providers/minimax",
            "getting-started/providers/moark",
            "getting-started/providers/modelscope",
            "getting-started/providers/moonshot-ai",
            "getting-started/providers/morph",
            "getting-started/providers/nebius",
            "getting-started/providers/neuralwatt",
            "getting-started/providers/novita",
            "getting-started/providers/ovhcloud",
            "getting-started/providers/parasail",
            "getting-started/providers/pareto-inference",
            "getting-started/providers/perplexity",
            "getting-started/providers/poolside",
            "getting-started/providers/prime-intellect",
            "getting-started/providers/reka",
            "getting-started/providers/sakana-ai",
            "getting-started/providers/sambanova",
            "getting-started/providers/sarvam",
            "getting-started/providers/scaleway",
            "getting-started/providers/siliconflow",
            "getting-started/providers/stackit",
            "getting-started/providers/stepfun",
            "getting-started/providers/subconscious",
            "getting-started/providers/synthetic",
            "getting-started/providers/telnyx",
            "getting-started/providers/thinking-machines",
            "getting-started/providers/tinfoil",
            "getting-started/providers/together-ai",
            "getting-started/providers/umans-ai",
            "getting-started/providers/upstage",
            "getting-started/providers/venice-ai",
            "getting-started/providers/vispark",
            "getting-started/providers/vultr-inference",
            "getting-started/providers/wafer",
            "getting-started/providers/wandb-inference",
            "getting-started/providers/xai",
            "getting-started/providers/z-ai",
            {
              type: "category",
              label: "Embedding Providers",
              collapsed: true,
              items: [
                "getting-started/providers/jina",
                "getting-started/providers/voyage",
              ],
            },
            {
              type: "category",
              label: "Voice Providers",
              collapsed: true,
              items: [
                "getting-started/providers/openai-tts",
                "getting-started/providers/elevenlabs",
                "getting-started/providers/deepgram",
                "getting-started/providers/azure-speech",
                "getting-started/providers/cartesia",
                "getting-started/providers/fish-audio",
              ],
            },
            {
              type: "category",
              label: "Media Generation Providers",
              collapsed: true,
              items: [
                "getting-started/providers/beatoven",
                "getting-started/providers/d-id",
                "getting-started/providers/elevenlabs-music",
                "getting-started/providers/heygen",
                "getting-started/providers/ideogram",
                "getting-started/providers/kling",
                "getting-started/providers/lyria",
                "getting-started/providers/musetalk",
                "getting-started/providers/recraft",
                "getting-started/providers/replicate",
                "getting-started/providers/runway",
                "getting-started/providers/stability",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "SDK",
      collapsed: true,
      items: [
        "sdk/index",
        "sdk/api-reference",
        "sdk/custom-tools-guide",
        "sdk/advanced-features",
        "sdk/framework-integration",
        "sdk/nestjs-integration",
      ],
    },
    {
      type: "category",
      label: "CLI",
      items: ["cli/index", "cli/commands", "cli/examples", "cli/advanced"],
    },
    {
      type: "category",
      label: "Decide",
      collapsed: false,
      items: [
        "features/decide-inference-type",
        "features/classifier-router",
        "features/classifier-router-jev-strategy",
        "features/classifier-router-catalog",
        "features/context-budget",
        "features/relevance-compaction",
        "features/tool-routing-decision-model",
        "features/rag-retrieval-planning",
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [
        "features/index",
        {
          type: "category",
          label: "Input & Output",
          collapsed: true,
          items: [
            "features/multimodal",
            "features/multimodal-chat",
            "features/pdf-support",
            "features/csv-support",
            "features/office-documents",
            "features/file-processors",
            "features/audio-input",
            "features/tts",
            "features/real-time-services",
          ],
        },
        {
          type: "category",
          label: "Generation",
          collapsed: true,
          items: [
            "features/structured-output",
            "features/image-generation",
            "features/video-generation",
            "features/video-director-mode",
            "features/video-analysis",
            "features/ppt-generation",
            "features/thinking-configuration",
            "advanced/streaming",
          ],
        },
        {
          type: "category",
          label: "Conversation & Memory",
          collapsed: true,
          items: [
            "features/conversation-history",
            "features/memory",
            "features/context-compaction",
            "features/hitl",
            "features/enterprise-hitl",
            "features/cli-loop-sessions",
          ],
        },
        {
          type: "category",
          label: "Safety & Quality",
          collapsed: true,
          items: [
            "features/guardrails",
            "features/guardrails-implementation",
            "features/auto-evaluation",
          ],
        },
        {
          type: "category",
          label: "Infrastructure",
          collapsed: true,
          items: [
            "features/authentication-providers",
            "features/provider-orchestration",
            "features/provider-fallback",
            "features/credential-validation",
            "features/regional-streaming",
            "features/mcp-tools-showcase",
            "features/skills",
            "features/embeddings",
            "features/rag",
            "features/observability",
            "features/task-manager",
            "features/autoresearch",
          ],
        },
        {
          type: "category",
          label: "Providers",
          collapsed: true,
          items: [
            "features/claude-subscription",
            "features/claude-subscription-testing",
            {
              type: "category",
              label: "Claude Proxy",
              collapsed: true,
              items: [
                "features/claude-proxy",
                "features/claude-proxy-architecture",
                "features/claude-proxy-config-reference",
                "features/claude-proxy-troubleshooting",
              ],
            },
            "features/real-time-services",
            "features/speech-agents",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "MCP",
      collapsed: true,
      items: [
        "mcp/overview",
        "mcp/integration",
        "mcp/http-transport",
        "mcp/configuration",
        "mcp/docs-server",
        "mcp/testing",
        "mcp/optimization",
        "guides/mcp/server-catalog",
      ],
    },
    {
      type: "category",
      label: "Memory",
      collapsed: true,
      items: [
        "memory/conversation",
        "memory/summarization",
        "advanced/memory-integration",
      ],
    },
    {
      type: "category",
      label: "Workflows",
      collapsed: true,
      items: [
        "features/workflow-engine",
        "workflows/orchestration",
        "workflows/ai-orchestration",
        "workflows/middleware",
        "workflows/custom-middleware",
        "workflows/error-handling",
        "advanced/builtin-middleware",
      ],
    },
    {
      type: "category",
      label: "Observability",
      collapsed: true,
      items: [
        "observability/telemetry",
        "observability/health-monitoring",
        "observability/provider-status",
        {
          type: "doc",
          id: "features/observability",
          label: "Observability Guide",
        },
      ],
    },
    {
      type: "category",
      label: "Deployment",
      collapsed: true,
      items: [
        "deployment/enterprise-proxy",
        "deployment/performance",
        "deployment/configuration",
        "deployment/configuration-management",
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "guides/index",
        {
          type: "category",
          label: "Frameworks",
          items: [
            "guides/frameworks/express",
            "guides/frameworks/nextjs",
            "guides/frameworks/fastify",
            "guides/frameworks/sveltekit",
          ],
        },
        {
          type: "category",
          label: "Server Adapters",
          collapsed: false,
          items: [
            "guides/server-adapters/index",
            "guides/server-adapters/hono",
            "guides/server-adapters/express",
            "guides/server-adapters/fastify",
            "guides/server-adapters/koa",
            "guides/server-adapters/security",
            "guides/server-adapters/deployment",
            "guides/server-adapters/errors",
            "guides/server-adapters/middleware",
            "guides/server-adapters/streaming",
            "guides/server-adapters/websocket",
            "guides/server-adapters/api-reference",
          ],
        },
        {
          type: "category",
          label: "Migration",
          items: [
            "guides/migration/from-langchain",
            "guides/migration/from-vercel-ai-sdk",
            "guides/migration-guide",
          ],
        },
        {
          type: "category",
          label: "Enterprise",
          items: [
            "guides/enterprise/multi-region",
            "guides/enterprise/multi-provider-failover",
            "guides/enterprise/load-balancing",
            "guides/enterprise/cost-optimization",
            "guides/enterprise/monitoring",
            "guides/enterprise/compliance",
            "guides/enterprise/audit-trails",
          ],
        },
        "guides/domain-specific",
        "guides/dynamic-models",
        "guides/session-management",
        "guides/redis-configuration",
        "guides/redis-migration",
        "guides/github-action",
        "guides/vector-stores",
      ],
    },
    {
      type: "category",
      label: "Cookbook",
      collapsed: true,
      items: [
        "cookbook/index",
        "cookbook/batch-processing",
        "cookbook/rate-limit-handling",
        "cookbook/multi-provider-fallback",
        "cookbook/streaming-with-retry",
        "cookbook/error-recovery",
        "cookbook/cost-optimization",
        "cookbook/tool-chaining",
        "cookbook/structured-output",
        "cookbook/conversation-summarization",
        "cookbook/context-window-management",
        "cookbook/basic-streaming",
        "cookbook/multimodal-images",
        "cookbook/provider-switching",
        "cookbook/embeddings-basics",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: true,
      items: [
        "tutorials/index",
        "tutorials/chat-app",
        "tutorials/rag",
        "tutorials/videos",
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsed: true,
      items: [
        "examples/index",
        "examples/basic-usage",
        "examples/advanced",
        "examples/business",
        "examples/mcp-tool-blocking-example",
        "guides/examples/code-patterns",
        "guides/examples/use-cases",
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      items: [
        "reference/index",
        "reference/error-codes",
        "reference/troubleshooting",
        "reference/provider-comparison",
        "reference/provider-behavior",
        "reference/provider-feature-compatibility",
        "reference/provider-capabilities-audit",
        "reference/analytics",
        "reference/provider-selection",
        "reference/server-configuration",
        "reference/faq",
        "advanced/analytics",
        "advanced/updated-provider-test-results",
        "advanced/auth-architecture",
      ],
    },
    {
      type: "category",
      label: "Demos",
      collapsed: true,
      items: ["demos/interactive", "demos/screenshots", "demos/videos"],
    },
    {
      type: "category",
      label: "Development",
      collapsed: true,
      items: [
        "development/index",
        "development/architecture",
        "development/testing",
        "development/testing-plan",
        "development/provider-testing",
        "development/factory-architecture",
        "development/factory-migration",
        "development/large-context-design",
        "development/versioning",
        "development/link-checking",
        "development/changelog-automation",
      ],
    },
    {
      type: "category",
      label: "Community",
      collapsed: true,
      items: [
        "community/contributing",
        "community/code-of-conduct",
        "community/changelog",
      ],
    },
  ],
};

export default sidebars;
